@startuml create_account
title <font size=24>Access Learning Materials Course Sequence</font>
skinparam sequenceMessageAlign center
autonumber

actor Student as act
boundary StudentPage as page
participant ":CourseRouter" as router
control CourseController as controler
participant ":Course" as context
database Database as db

act -> page: View List Course Page
activate page
page -> router: endpoint /api/course/list_materials
activate router
router -> controler: Call ListMaterials(courseName) method
activate controler
controler -> context: Call FindMany(courseName) method
activate context
context -> db: Query database
activate db
db --> context: Return Course
deactivate db
context --> controler: Return Course
deactivate context
alt number < 0
    autonumber 7.1
    controler --> router: Return message error
    autonumber 7.1.1
    router --> page: Return message error
    page --> act: Show message error
else number > 0
    autonumber 7.2
    controler --> router: Return message error
    autonumber 7.2.1
    deactivate controler
    router --> page: Return message successful
    deactivate router
    page --> act: Show message successful and redirect to list Course
    deactivate page
end
@enduml