@startuml ReceiveNotifications
|Student|
start
:1. View notifications;
|StudentDashboard|
:2. Fetch notifications;
|NotificationController|
:3. Get notifications;
|Notification|
:4. Return notifications;
|NotificationController|
:5. Return notifications;
|StudentDashboard|
:6. Show notifications;
stop
@enduml