@startuml CreateUserAccount
title <font size=24>Create Account Sequence</font>
skinparam sequenceMessageAlign center
autonumber

actor Admin as act
boundary AdminPage as page
participant ":UsernRouter" as router
control UserController as controler
participant ":User" as context
database Database as db

loop Input invalid
    act -> page: Enter new information of User and click "Lưu" button
    activate page
    page -> page: Validation input
    activate page

    deactivate page
    autonumber 3
    page --> act: Display invalid input
end

autonumber 4
page -> router: endpoint /api/user/create_account
activate router
router -> controler: Call CreateNewUser(userData) method
activate controler
controler -> context: Call FindOne(userData.email) method
activate context
context -> db: Query database
activate db
db --> context: Return user
deactivate db
context --> controler: Return User
deactivate context
controler -> controler: Check null User
activate controler
deactivate controler
opt User not null
    autonumber 10.1
    controler --> router: Return "User had existed"
    router --> page: Return "User had existed"
    page --> act: Return "User had existed"
end
autonumber 11
controler -> context: Call newUser.save(userData) method
activate context
context -> db: Insert database
activate db
db --> context: Return number
deactivate db
context --> controler: Return number
deactivate context
alt number < 0
    autonumber 14.1
    controler --> router: Return message error
    autonumber 14.1.1
    router --> page: Return message error
    page --> act: Show message error
else number > 0
    autonumber 14.2
    controler --> router: Return message error
    autonumber 14.2.1
    deactivate controler
    router --> page: Return message successful
    deactivate router
    page --> act: Show message successful and redirect to list User
    deactivate page
end
@enduml