@startuml ManageAssignments
|Teacher|
start
:Go to assignment tab;
|AssignmentUI|
:Show assignment options;
|Teacher|
:Create/edit assignments;
|AssignmentUI|
:Submit assignment data;
|AssignmentController|
:Store assignment;
|Assignment|
:Confirm stored;
|AssignmentController|
:Confirm save;
|AssignmentUI|
:Show updated assignments;
stop
@enduml