@startuml create_account
title <font size=24>Create Submission Student Sequence</font>
skinparam sequenceMessageAlign center
autonumber

actor Student as act
boundary StudentPage as page
participant ":SubmissionRouter" as router
control SubmissionController as controler
participant ":Submission" as context
database Database as db

loop Input invalid
    act -> page: Enter new information submit and click "Lưu" button
    activate page
    page -> page: Validation input
    activate page
    deactivate page
    autonumber 3
    page --> act: Display invalid input
end

autonumber 4
page -> router: endpoint /api/submission/create_submit_student
activate router
router -> controler: Call CreateNewSubmit(assignmentName, submitData) method
activate controler
controler -> context: Call FindOne(assignmentName) method
activate context
context -> db: Query database
activate db
db --> context: Return Submission
deactivate db
context --> controler: Return Submission
deactivate context
controler -> controler: Check null Submission
activate controler
deactivate controler
opt Submission not null
    autonumber 10.1
    controler --> router: Return "Assignment no existed"
    router --> page: Return "Assignment no existed"
    page --> act: Return "Assignment no existed"
end
autonumber 11
controler -> context: Call newSubmission.save(submitData) method
activate context
context -> db: Insert database
activate db
db --> context: Return number
deactivate db
context --> controler: Return number
deactivate context
alt number < 0
    autonumber 14.1
    controler --> router: Return message error
    autonumber 14.1.1
    router --> page: Return message error
    page --> act: Show message error
else number > 0
    autonumber 14.2
    controler --> router: Return message error
    autonumber 14.2.1
    deactivate controler
    router --> page: Return message successful
    deactivate router
    page --> act: Show message successful and redirect to list Submission
    deactivate page
end
@enduml