@startuml AccessLearningMaterials
|Student|
start
:1. Open course page;
|StudentDashboard|
:2. Request materials;
|MaterialController|
:3. Fetch materials;
|Material|
:4. Return materials;
|MaterialController|
:5. Provide materials list;
|StudentDashboard|
:6. Show materials (if enrolled);
stop
@enduml