#set page(width: auto)

== List 07 - Course Management

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Course Code],
  [Single line Of Text],
  [Course Code],
  [No],
  [Yes],
  [],
  [This field describes the unique course code.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Course Name],
  [Single line Of Text],
  [Course Name],
  [No],
  [Yes],
  [],
  [This field describes the course name or title.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Credits],
  [Number],
  [Credits],
  [No],
  [Yes],
  [],
  [This field describes the number of credits for the course.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Description],
  [Rich Text],
  [Description],
  [No],
  [No],
  [],
  [This field describes the course description.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Status],
  [Drop-Down List],
  [Status],
  [No],
  [Yes],
  [Active],
  [Value list:\n- Active\n- Inactive],
  [],
  [],
  [],
  [],
  [],
  [],

  [6], [], [Button], [Edit], [No], [], [], [This button opens a form to update course information.], [], [], [], [], [],

  [7],
  [],
  [Button],
  [Delete],
  [No],
  [],
  [],
  [This button displays a confirmation dialog to delete the course.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Administrator has permission to create courses.],
  [3], [Updating Rule], [Only Administrator has permission to update course information.],
  [4], [Deleting Rule], [Only Administrator has permission to delete courses.],
  [5], [Reading Rule], [All authenticated users can view course list.],
)

== List 08 - Class Management

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Class Code],
  [Single line Of Text],
  [Class Code],
  [No],
  [Yes],
  [],
  [This field describes the unique class code.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Class Name],
  [Single line Of Text],
  [Class Name],
  [No],
  [Yes],
  [],
  [This field describes the class name or section.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Course],
  [Single line Of Text],
  [Course],
  [No],
  [Yes],
  [],
  [This field describes which course this class belongs to.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Capacity],
  [Number],
  [Capacity],
  [No],
  [Yes],
  [],
  [This field describes the maximum student capacity for the class.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Enrolled Students],
  [Number],
  [Enrolled Students],
  [No],
  [No],
  [],
  [This field shows the current number of enrolled students.],
  [],
  [],
  [],
  [],
  [],
  [],

  [6], [], [Button], [Edit], [No], [], [], [This button opens a form to update class information.], [], [], [], [], [],

  [7],
  [],
  [Button],
  [Delete],
  [No],
  [],
  [],
  [This button displays a confirmation dialog to delete the class.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Administrator has permission to create classes.],
  [3], [Updating Rule], [Only Administrator has permission to update class information.],
  [4], [Deleting Rule], [Only Administrator has permission to delete classes.],
  [5], [Reading Rule], [Administrators and Teachers can view class list.],
)

== List 09 - Student Enrollment Management

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Student ID],
  [Single line Of Text],
  [Student ID],
  [No],
  [Yes],
  [],
  [This field describes the unique student identifier.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Student Name],
  [Single line Of Text],
  [Student Name],
  [No],
  [Yes],
  [],
  [This field describes the full name of the student.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Email],
  [Single line Of Text],
  [Email],
  [No],
  [Yes],
  [],
  [This field describes the student email address.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Enrolled Courses],
  [Number],
  [Enrolled Courses],
  [No],
  [No],
  [],
  [This field shows the number of courses the student is enrolled in.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Enrollment Status],
  [Drop-Down List],
  [Status],
  [Yes],
  [Yes],
  [Active],
  [Value list:\n- Active\n- Inactive\n- Suspended],
  [],
  [],
  [],
  [],
  [],
  [],

  [6],
  [],
  [Button],
  [View Details],
  [No],
  [],
  [],
  [This button opens student enrollment details and course information.],
  [],
  [],
  [],
  [],
  [],

  [7],
  [],
  [Button],
  [Remove],
  [No],
  [],
  [],
  [This button displays a confirmation dialog to remove the enrollment.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Administrator has permission to create student enrollments.],
  [3], [Updating Rule], [Only Administrator has permission to update enrollment information.],
  [4], [Deleting Rule], [Only Administrator has permission to delete enrollments.],
  [5], [Reading Rule], [Administrators and Teachers can view enrollment list.],
)

== List 10 - Course Assignments

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Assignment Title],
  [Single line Of Text],
  [Title],
  [No],
  [Yes],
  [],
  [This field describes the assignment title or name.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Course],
  [Single line Of Text],
  [Course],
  [No],
  [Yes],
  [],
  [This field describes which course this assignment belongs to.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Due Date],
  [Date Time],
  [Due Date],
  [No],
  [Yes],
  [],
  [This field describes the assignment due date.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Total Points],
  [Number],
  [Total Points],
  [No],
  [Yes],
  [],
  [This field describes the maximum points for the assignment.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Submissions],
  [Number],
  [Submissions],
  [No],
  [No],
  [],
  [This field shows the number of received submissions.],
  [],
  [],
  [],
  [],
  [],
  [],

  [6],
  [],
  [Button],
  [View],
  [No],
  [],
  [],
  [This button opens the assignment details and student submissions.],
  [],
  [],
  [],
  [],
  [],

  [7], [], [Button], [Edit], [No], [], [], [This button opens a form to edit the assignment.], [], [], [], [], [], [8],
  [],
  [Button],
  [Delete],
  [No],
  [],
  [],
  [This button displays a confirmation dialog to delete the assignment.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Teacher has permission to create assignments.],
  [3], [Updating Rule], [Only Teacher can update assignment before due date.],
  [4], [Deleting Rule], [Only Teacher has permission to delete assignments.],
  [5], [Reading Rule], [Teachers and Students can view assignment list.],
)

== List 11 - Course Materials

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Material Title],
  [Single line Of Text],
  [Title],
  [No],
  [Yes],
  [],
  [This field describes the title of the course material.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Course],
  [Single line Of Text],
  [Course],
  [No],
  [Yes],
  [],
  [This field describes which course the material belongs to.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [File Name],
  [Single line Of Text],
  [File Name],
  [No],
  [Yes],
  [],
  [This field describes the uploaded file name.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Upload Date],
  [Date Time],
  [Upload Date],
  [No],
  [No],
  [],
  [This field shows when the material was uploaded.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Description],
  [Rich Text],
  [Description],
  [No],
  [No],
  [],
  [This field describes the material content or purpose.],
  [],
  [],
  [],
  [],
  [],
  [],

  [],
  [6],
  [],
  [Button],
  [Download],
  [No],
  [],
  [],
  [This button allows users to download the material file.],
  [],
  [],
  [],
  [],
  [],

  [], [7], [], [Button], [Edit], [No], [], [], [This button opens a form to edit material details.], [], [], [], [], [],
  [],
  [8],
  [],
  [Button],
  [Delete],
  [No],
  [],
  [],
  [This button displays a confirmation dialog to delete the material.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Teacher has permission to upload course materials.],
  [3], [Updating Rule], [Only Teacher can update material details.],
  [4], [Deleting Rule], [Only Teacher has permission to delete materials.],
  [5], [Reading Rule], [Teachers and Students can view material list.],
)

== List 12 - Assignment Submissions

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Student Name],
  [Single line Of Text],
  [Student Name],
  [No],
  [Yes],
  [],
  [This field describes the name of the student who submitted.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Assignment],
  [Single line Of Text],
  [Assignment],
  [No],
  [Yes],
  [],
  [This field describes which assignment the submission belongs to.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Submission Date],
  [Date Time],
  [Submission Date],
  [No],
  [No],
  [],
  [This field shows when the submission was made.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Status],
  [Drop-Down List],
  [Status],
  [No],
  [Yes],
  [Submitted],
  [Value list:\n- Submitted\n- Graded\n- Late],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Score],
  [Number],
  [Score],
  [Yes],
  [No],
  [],
  [This field describes the score given to the submission.],
  [],
  [],
  [],
  [],
  [],
  [],

  [6], [], [Button], [View], [No], [], [], [This button opens the submission details and content.], [], [], [], [], [],

  [7],
  [],
  [Button],
  [Grade],
  [No],
  [],
  [],
  [This button opens a form to grade and provide feedback.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [If any mandatory field is left blank, system shows error message.],
  [2], [Creating Rule], [Only Students can create assignment submissions.],
  [3], [Updating Rule], [Students can update submissions before due date, Teachers can grade anytime.],
  [4], [Deleting Rule], [Only Teacher has permission to delete submissions.],
  [5], [Reading Rule], [Teachers and Students can view their own submission list.],
)

== List 13 - Feedback and Grading

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Student Name],
  [Single line Of Text],
  [Student Name],
  [No],
  [Yes],
  [],
  [This field describes the name of the student being evaluated.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Assignment/Item],
  [Single line Of Text],
  [Assignment/Item],
  [No],
  [Yes],
  [],
  [This field describes the assignment or item being graded.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Score],
  [Number],
  [Score],
  [Yes],
  [Yes],
  [],
  [This field describes the numeric score or grade.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Feedback Comment],
  [Rich Text],
  [Feedback Comment],
  [Yes],
  [No],
  [],
  [This field contains detailed feedback for the student.],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Graded Date],
  [Date Time],
  [Graded Date],
  [No],
  [No],
  [],
  [This field shows when the item was graded.],
  [],
  [],
  [],
  [],
  [],
  [],

  [6],
  [],
  [Button],
  [View],
  [No],
  [],
  [],
  [This button opens the full feedback and grading details.],
  [],
  [],
  [],
  [],
  [],

  [7], [], [Button], [Edit], [No], [], [], [This button opens a form to edit score and feedback.], [], [], [], [], [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [Score must be within the assignment's maximum points.],
  [2], [Creating Rule], [Only Teacher has permission to create feedback and grades.],
  [3], [Updating Rule], [Only Teacher can update feedback and grades.],
  [4], [Deleting Rule], [Only Teacher has permission to delete feedback records.],
  [5], [Reading Rule], [Teachers and Students can view feedback for their own submissions.],
)

== List 14 - Notifications

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [Message],
  [Rich Text],
  [Message],
  [No],
  [Yes],
  [],
  [This field describes the notification message content.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Type],
  [Drop-Down List],
  [Type],
  [No],
  [Yes],
  [],
  [Value list:\n- Assignment\n- Grade\n- Enrollment\n- Course Update\n- System],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Sent Date],
  [Date Time],
  [Sent Date],
  [No],
  [No],
  [],
  [This field shows when the notification was sent.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Status],
  [Drop-Down List],
  [Status],
  [No],
  [Yes],
  [Unread],
  [Value list:\n- Unread\n- Read\n- Archived],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Related Item],
  [Single line Of Text],
  [Related Item],
  [No],
  [No],
  [],
  [This field describes the related assignment, course, or user.],
  [],
  [],
  [],
  [],
  [],
  [],

  [], [6], [], [Button], [View], [No], [], [], [This button opens the full notification details.], [], [], [], [], [],
  [],
  [7],
  [],
  [Button],
  [Delete],
  [No],
  [],
  [],
  [This button archives or deletes the notification.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [Notification message cannot be empty.],
  [2], [Creating Rule], [System and Teachers can create notifications.],
  [3], [Updating Rule], [Notifications can be marked as read or archived by users.],
  [4], [Deleting Rule], [Users can delete their own notifications.],
  [5], [Reading Rule], [Users can view notifications sent to them.],
)

== List 15 - User Management

=== List Design

#table(
  columns: 14,
  [*\#*],
  [*Column Name*],
  [*Column Type*],
  [*Label*],
  [*Editable*],
  [*Mandatory*],
  [*Default Value*],
  [*Description*],
  [*Design Solution*],
  [*Extracting UT*],
  [*Pre-Processing UT*],
  [*Transforming UT*],
  [*Post-Processing UT*],
  [*Comment*],

  [1],
  [User ID],
  [Single line Of Text],
  [User ID],
  [No],
  [Yes],
  [],
  [This field describes the unique user identifier.],
  [],
  [],
  [],
  [],
  [],
  [],

  [2],
  [Full Name],
  [Single line Of Text],
  [Full Name],
  [No],
  [Yes],
  [],
  [This field describes the user's full name.],
  [],
  [],
  [],
  [],
  [],
  [],

  [3],
  [Email],
  [Single line Of Text],
  [Email],
  [Yes],
  [Yes],
  [],
  [This field describes the user email address.],
  [],
  [],
  [],
  [],
  [],
  [],

  [4],
  [Role],
  [Drop-Down List],
  [Role],
  [Yes],
  [Yes],
  [],
  [Value list:\n- Administrator\n- Teacher\n- Student],
  [],
  [],
  [],
  [],
  [],
  [],

  [5],
  [Status],
  [Drop-Down List],
  [Status],
  [Yes],
  [Yes],
  [Active],
  [Value list:\n- Active\n- Inactive\n- Suspended],
  [],
  [],
  [],
  [],
  [],
  [],

  [6],
  [Last Login],
  [Date Time],
  [Last Login],
  [No],
  [No],
  [],
  [This field shows the user's last login date and time.],
  [],
  [],
  [],
  [],
  [],
  [],

  [],
  [7],
  [],
  [Button],
  [View],
  [No],
  [],
  [],
  [This button opens user details and activity history.],
  [],
  [],
  [],
  [],
  [],

  [], [8], [], [Button], [Edit], [No], [], [], [This button opens a form to edit user information.], [], [], [], [], [],
  [],
  [9],
  [],
  [Button],
  [Deactivate],
  [No],
  [],
  [],
  [This button changes the user status to inactive.],
  [],
  [],
  [],
  [],
  [],
)

=== Custom Business Rules

#table(
  columns: 3,
  [*\#*], [*Rule Name*], [*Rule Description*],
  [1], [Validation Rules], [Email must be unique and in valid format.],
  [2], [Creating Rule], [Only Administrator has permission to create users.],
  [3], [Updating Rule], [Only Administrator can update user information.],
  [4], [Deleting Rule], [Only Administrator can deactivate or delete users.],
  [5], [Reading Rule], [Only Administrator can view user management list.],
)
