@startuml ViewPlatformStats
|Admin|
start
:1. Open dashboard;
|AdminDashboard|
:2. Request stats;
|StatsController|
:3. Aggregate data;
|PlatformStats|
:4. Return stats;
|StatsController|
:5. Return stats;
|AdminDashboard|
:6. Show charts;
stop
@enduml