#table(
  columns: 4,
  [*User Story*], [*Admin*], [*Teacher*], [*Student*],
  [1.1 Sign up], [], [], [✓],
  [1.2 Login/Logout], [✓], [✓], [✓],
  [1.3 Assign Roles], [✓], [], [],
  [1.4 Create Teacher Account], [✓], [], [],
  [2.1 Manage Courses], [✓], [], [],
  [2.2 Manage Classes], [✓], [✓], [],
  [2.3 Manage Student Enrollments], [✓], [], [],
  [2.4 View Enrolled Courses], [], [✓], [✓],
  [2.5 Manage Teacher-Class Assignment], [✓], [], [],
  [2.6 Self-Enroll in Courses], [], [], [✓],
  [3.1 Manage Course Materials], [✓], [✓], [],
  [3.2 Access Learning Materials], [], [✓], [✓],
  [4.1 Manage Assignments], [], [✓], [],
  [4.2 Submit Assignments], [], [], [✓],
  [4.3 Review Submissions & Comment], [], [✓], [],
  [4.4 View Feedback], [], [], [✓],
  [5.1 Send Notifications], [✓], [✓], [],
  [5.2 Receive Notifications], [✓], [✓], [✓],
  [6.1 View Submissions], [], [✓], [],
  [6.2 View My Submissions], [], [], [✓],
  [7.1 View Platform Stats], [✓], [], [],
  [7.2 Manage User Accounts], [✓], [], [],
  [7.3 Update System Settings], [✓], [], [],
)
