= List Classes

- Epic: Class Management
- Actor: Admin
- MVP: Yes
- BR: BR-CLS-4
- Description / Notes: View a list of all classes.
- As a: Admin
- I want to: See a list of all classes
- So that: I can manage them effectively.
- Trigger: The admin navigates to the class management section.
- Pre-condition:
    - The admin must be logged into the system.
    - The admin must have class management permissions.
- Post-condition:
    - A list of all classes is displayed, showing relevant details (e.g., class name, course, teacher).
- Solution (Step-by-Step):
  - Open class management panel.
  - The list of classes is displayed.
  - The admin can use pagination to navigate through the list.
  - The admin can use search or filter options to find specific classes.
