= Create Teacher Account

- Epic: User Authentication & Roles
- Actor: Admin
- MVP: No
- BR: BR4
- Description / Notes: Teachers must be manually added
- As a: Admin
- I want to: Make teacher's account
- So that: New users can't be teachers by default
- Trigger: A new teacher needs an account.
- Pre-condition:
    - Admin is logged in.
- Post-condition:
    - Teacher account is created and an email is sent.
- Solution (Step-by-Step):
  - Admin opens create user form
  - Fill in teacher info
  - Select "Teacher" role
  - Backend creates account
  - Send activation or temp password email