@startuml ViewFeedback
|Student|
start
:1. Open submitted assignment;
|SubmissionUI|
:2. Fetch feedback;
|SubmissionController|
:3. Get feedback;
|Feedback|
:4. Return feedback;
|SubmissionController|
:5. Return feedback;
|SubmissionUI|
:6. Show feedback/comments;
stop
@enduml