apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: uit-se357-backend:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "npx prisma db push"]
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
